### ISSUE TITLE
Duplicate content in shopping cart

### ISSUE THREAD

**Issue by LeadDogAd** [Prospress/woocommerce-subscribe-all-the-things#395] opened 2018-12-17 20:14 UTC
Hello,

I need a little help please. When I add subscriptions to a product the subscription options are duplicated in the shopping cart. Would you please have a look and let me know what to do. 

I've added subscriptions to the product below. If you add them to the cart you will see that everything duplicates:

https://catiesorganics.com/product/caties-calcium

Thank you in advance for any help you can give me!!

**Comment by franticpsyx** [comment] 2018-12-29 00:30
Hey @LeadDogAd -- I'm afraid this isn't something we can replicate. The issue is most likely caused by a theme/plugin conflict. To address this:

1. Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.
2. If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.

Closing, but feel free to let us know what you've found after following these steps!

**Closed by franticpsyx** 2018-12-29 00:30 UTC

**Comment by LeadDogAd** [comment] 2019-01-09 22:18
I've done this. The issue is your plugin. This does not happen unless your plugin is activated.
