### ISSUE TITLE
Performance issues in SATT 2.1.1

### ISSUE THREAD

**Issue by giulianorapoz** [Prospress/woocommerce-subscribe-all-the-things#332] opened 2018-08-12 12:55 UTC
Since 2.1.1 the performance of adding an entire cart to a subscription has significantly slowed down. What used to be 2 seconds has turned into 5/6 seconds. - Makes the plugin quite unusable.

Can provide further diagnostics if required, but I have tested by rolling back to version 2.0.2 and performance is back to normal.

**Comment by franticpsyx** [comment] 2018-08-13 06:00
> adding an entire cart to a subscription has significantly slowed down

Note that the "add-cart-to-subscription" feature didn't exist in 2.0, so I assume you are referring to the usual checkout flow when a cart subscription is selected?

**Comment by franticpsyx** [comment] 2018-08-13 06:36
I've had a look at this -- there are no costly SATT function calls under the same circumstances in v2.1.

If you are experiencing performance issues in the cart page when a cart subscription option is selected, they might be caused by an issue in https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/templates/cart/cart-add-to-subscription.php#L38 -- the `do_action` call here should be wrapped in a `if ( $is_checked ) { }` block, otherwise all matching subscriptions will be retrieved on every cart page load. Obviously, this needs to be fixed.

**Comment by franticpsyx** [comment] 2018-08-13 06:41
I have updated `master` with the discussed patch. Closing this one out, but feel free to add any relevant details if the original issue isn't resolved.

**Closed by franticpsyx** 2018-08-13 06:41 UTC
Labels: housekeeping, refactor

**Comment by giulianorapoz** [comment] 2018-08-13 08:44
@franticpsyx Just some additional clarification:

The "Subscribe to cart feature" is available in v2.0.2 - That is what I rolled back to in order to test performance. So I am still referring to that feature as originally mentioned.

I haven't done any deep debugging, but my initial performance testing shows that in v2.1.1 the new "add cart to **an existing** subscription" is causing the slowdown in performance. Perhaps there is a significant function call used to process this.

Where can I find the xdump files? Happy to provide these and help.

**Comment by franticpsyx** [comment] 2018-08-13 08:53
See 
https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/332#issuecomment-412422152 and https://github.com/Prospress/woocommerce-subscribe-all-the-things/commit/03999e96ed2f278c157f7cbeced2afb107acfbaa

The slowdown should be resolved in `master`.

**Comment by giulianorapoz** [comment] 2018-08-13 08:57
@franticpsyx Thanks - will re-test and let you know.

**Comment by thenbrent** [comment] 2018-08-14 04:09
> the new "add cart to an existing subscription" is causing the slowdown in performance. Perhaps there is a significant function call used to process this.

I've looked into this and that's caused by a known issue in Subscriptions core. It's not an issue with SATT.

Queries to get a user's subscriptions for a purpose like this become slow on large sites, in particular, sites with a large `wp_postmeta` tables. The root issue with that was addressed in Subscriptions 2.3, which introduced a cache for that data. However, we recently found the new cache wasn't being used via `wcs_get_subscriptions()`, which is the method being used by SATT.

The next version of Subscriptions, v2.3.5, or a version soon after will include a fix for that.

If you would like to get pre-release access to the patches, please submit a ticket to support: https://woocommerce.com/my-account/create-a-ticket/ :)

@franticpsyx if you're curious, the patches are in this PR: https://github.com/Prospress/woocommerce-subscriptions/pull/2856/ (this link/page will 404 for anyone not added to the private `Prospress/woocommerce-subscriptions` repo).

**Comment by franticpsyx** [comment] 2018-08-14 07:37
@thenbrent 💯 

The intent in SATT was that whatever slowness existed there shouldn't affect everyone when the cart page is loaded. I remember chatting about this in HI when we briefly went through the add-to-scubscription "specs" in product/cart context.

On single-product pages, the Add-to-subscription checkbox can't be pre-selected on page load, while in the cart page, where contents may get re-loaded when the cart changes, or a new subscription scheme is chosen, we want to maintain the state of the Add-to-sub checkbox.

That's why the template includes the table of subscriptions in the latter case only. When writing the template code, I forgot to prevent the content from pre-loading when a subscription scheme is chosen but the add-to-sub checkbox hasn't been ticked ;)

**Comment by giulianorapoz** [comment] 2018-08-20 13:54
@franticpsyx I have re-tested with fresh pull of master and can confirm that performance issue has been resolved (perhaps temporarily, as you suggest @thenbrent will be fixed in Subscriptions v.2.3.5)

Thanks!
