### ISSUE TITLE
UX Request - Add to existing subscription table

### ISSUE THREAD

**Issue by SundayDriver** [Prospress/woocommerce-subscribe-all-the-things#356] opened 2018-10-03 16:28 UTC
<img width="353" alt="screen shot 2018-10-03 at 12 12 01 pm" src="https://user-images.githubusercontent.com/77760/46423905-b299fc00-c705-11e8-9822-e36b6e0c0783.png">

Observation:
The "add to subscription table" that comes up after choosing to add to a subscription is too wide and does not offer much flexibility. Tables are difficult to manage via CSS, although I agree this is probably tabular data. Our store is unlikely to have people with more than 1 subscription. I'm not sure what the best UX experience is that would fit all stores, but there is probably a better solution than the current display. 

My recommendations: 
At the least, the first column should be the Actions. It can have the "add" and "view" options under the subscription number. I question if you need the "view" button since the number is already linked. 
Also, I prefer not to take users away from the product page. I would like "view" to open in a new tab or pop-up. 

Oh and you may want to and add the overflow:scroll option just in case since tables cannot flex well.

**Comment by SundayDriver** [comment] 2018-10-03 16:32
PS- I would love to be able to donate to help you guys. Is there a place for that?

**Comment by thenbrent** [comment] 2018-10-03 22:57
@SundayDriver this is a duplicate of the issue I created yesterday: https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/353

**Closed by thenbrent** 2018-10-03 22:57 UTC
