### ISSUE TITLE
cart subscription options break product quantity

### ISSUE THREAD

**Issue by neoseeyou** [Prospress/woocommerce-subscribe-all-the-things#392] opened 2018-12-03 14:48 UTC
Hello

When i activate the subscription in my cart, the product's quantity disappear. I need to reload the page to display the quantity again.

![prtscr-capture_9](https://user-images.githubusercontent.com/24687907/49380817-d338ff00-f712-11e8-90d3-966253bd5b07.jpg)

Thank you

**Comment by franticpsyx** [comment] 2018-12-29 00:17
Hey @neoseeyou -- this is most likely caused by a theme/plugin conflict. Here's how to address this type of issue:

* Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.
* If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.

Closing as we're not able to replicate this, but feel free to add further details here if needed.

**Closed by franticpsyx** 2018-12-29 00:17 UTC
