### ISSUE TITLE
Apply discounts when adding product to an existing subscription

### ISSUE THREAD

**Issue by SundayDriver** [Prospress/woocommerce-subscribe-all-the-things#349] opened 2018-09-21 15:58 UTC
Kind greetings, On our website we use the STAT plugin with the Subscriptions and Toolbox. Our combo packs have a 10% discount when you subscribe monthly. The 10% discount is applied correctly to the first order, but if they "add to an existing subscription" it does not apply the 10% discount.

**Comment by thenbrent** [comment] 2018-09-23 23:57
Hi @SundayDriver that's not something we've built-in to the _Add to Subscription_ feature. I'll mark this as a feature request and keep it open to track popularity of the request. If it proves popular enough, we can add it to the [roadmap](https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap).

**Comment by SundayDriver** [comment] 2018-09-24 01:58
Thanks Brent! This is very confusing to our customers since they normally get the 10% off for the subscription if they add it any other way. Can we pay for some custom development? We are happy to purchase some dev time as this is very important to our business!

**Comment by thenbrent** [comment] 2018-09-24 02:50
Hi @SundayDriver we don't offer custom development, but some other developers who do watch this repo, so they may reach out. You will also be able to find a developer to help with this feature via: http://codeable.io/

Please encourage whoever you work with to submit the code as a Pull Request to this extension also. That may make it easier to develop for them, as they won't need special ways to hook into the code from the outside. It will also mean then we will maintain it in future so you don't need to worry about it being broken by an update.

**Comment by thenbrent** [comment] 2018-10-02 05:45
@SundayDriver I can't reproduce this issue.

When I add a simple product with a scheme that provides a 10% discount to an existing subscription, the discounted price is used.

Here's a quick video demonstrating this: http://pic.pros.pr/2fe7ea798888

Can you please provide more details? Ideally, a quick video showing the issue on your site?

Also how are you creating the "combo packs"?

**Comment by SundayDriver** [comment] 2018-10-02 22:02
Hi Brent! I sincerely appreciate your help! 

Check out this video here: https://cl.ly/233b80e2f883

What I learned:
1- You CAN add to an existing subscription. I did not realize you have to click the "add" button instead of "add to cart" after checking the box for "Add to existing subscription" 
2- The HTML table doesn't fit in the box we have for the add to cart information. I need to figure out something for this on my end, but it would be nice if you guys could also trim the amount of content. 
3- One thing that would make it less confusing is to disable the add to cart button when they choose to add to an existing subscription. 
4- When adding to an existing subscription, the variations are lost so we do not know what customers have ordered.

So it looks like customers are just confused by the interface. The title of this issue should be "variations lost when adding to subscription & interface suggestions"  :)

**Comment by thenbrent** [comment] 2018-10-03 01:39
> It looks like you fixed the discount not working in the latest release, 

That's not actually SATT there. I'm pretty sure that's Toolbox. That's also why the discount wasn't being added - because SATT sets the discount on the subscription scheme. Toolbox has no awareness of that.

> however the older dropdown vs table was much better.

You could continue to use Toolbox's _Add to subscription_ functionality and disable SATT's. It won't honour the discounts though, as they come from SATT. You could ask Gabor, the Toolbox dev to look at integrating with SATT discounts / schemes. He's a very responsive developer (and is sometimes active on this repo too).

> What I learned:

We've learned a lot too!

> The HTML table doesn't fit in the box we have

I've created https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/353 to keep track of that.

> disable the add to cart button when they choose to add to an existing subscription

I've opened https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/354 to keep track of that. Disabling it could lead to other confusing behaviour so it's not guaranteed to be added, but it's a suggestion worth keeping in mind none-the-less.

> When adding to an existing subscription, the variations are lost so we do not know what customers have ordered.

I've opened https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/355 to continue investigating that. We don't technically support subscription schemes on variations yet, so I wouldn't be surprised if that's not working yet, but I'll confirm and follow up on #355.

I'm going to close this one now as there's so many separate issues, and the root issue is related to Toolbox + SATT compatibility rather than being a bug in SATT. :)

**Closed by thenbrent** 2018-10-03 01:39 UTC
Labels: bug:unconfirmed
