### ISSUE TITLE
Discount not applying to subscriptions

### ISSUE THREAD

**Issue by SundayDriver** [Prospress/woocommerce-subscribe-all-the-things#350] opened 2018-09-27 17:59 UTC
We give our customers 10% off when they subscribe to a product monthly. 

There are some orders where it doesn't keep the 10% discount on renewal orders. 

I believe I have narrowed it down to orders that use a coupon on their initial order. They get the coupon discount + the 10% subscriber discount on that first order, but on the renewal they are charged full price. 

I agree that the coupon should not be on the renewal orders, but I would like to keep the 10% subscriber discount for the life of the subscription. It works correctly when there is not a coupon used.

**Comment by franticpsyx** [comment] 2018-09-28 05:52
Hey @SundayDriver -- is this related with https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/349 ?

**Comment by SundayDriver** [comment] 2018-09-28 17:29
Yes I think it might be actually. I am not 100% sure. If so I apologize for the duplicate. At first I just noticed that the customer had used a coupon on their initial order, but upon further investigation, it looks like the customer may have tried to change their variations of the product. 

Customers seem to want to change the flavors inside of the combo pack we offer. https://www.kindjuice.com/vape-juice/islander-survival-pack-of-5-15ml/

We really need this to work! Any workaround or solution would be very much appreciated.

**Comment by thenbrent** [comment] 2018-10-02 00:16
Hi @SundayDriver I'm going to close this one as I couldn't reproduce and it does sound like it's the same issue as #349, which we'll leave open as it's a bug.

> Any workaround or solution would be very much appreciated.

Are you asking for more than the discounted price to work? If so, please open a new issue. If not, we'll look into that on #349, but please bear in mind the [caveats about support](https://github.com/Prospress/woocommerce-subscribe-all-the-things#support), and know that we will accept patches from 3rd party developers for the fix if you need it sooner than we can work on it.

**Closed by thenbrent** 2018-10-02 00:16 UTC
Labels: bug:unconfirmed
