### ISSUE TITLE
Subscribe to Cart - breaks when updating quantity

### ISSUE THREAD

**Issue by vuongtng** [Prospress/woocommerce-subscribe-all-the-things#91] opened 2016-12-25 01:46 UTC
The subscribe to cart function works fine until the customer increases or decreases quantity in cart after selecting a subscribe to cart plan. After updating the cart, the customer is presented with a -1 on a blank page. If pressing back, the quantities appear to be updated and working normal, also continuing to update quantities seem to work thereafter.

The blank page with a -1 has the url of **/cart/?wc-ajax=wcsatt_update_cart_option**

**Comment by pprotschka** [comment] 2016-12-25 09:07
See #81

**Comment by pprotschka** [comment] 2016-12-25 09:07
Sorry I mean #82

**Comment by franticpsyx** [comment] 2016-12-26 09:54
Duplicate of https://github.com/Prospress/woocommerce-subscribe-all-the-things/issues/82

**Closed** 2016-12-26 09:54 UTC
