### ISSUE TITLE
NYP Variations + SATT missing subscription options

### ISSUE THREAD

**Issue by helgatheviking** [Prospress/woocommerce-subscribe-all-the-things#317] opened 2018-06-15 11:14 UTC
Subscription options don't appear for a variation that is NYP.

![image](https://user-images.githubusercontent.com/507025/41465238-3ad69936-70d8-11e8-9695-b5dfca1db2bf.png)

It appears to be due to the fact that both NYP and SATT are setting the price dynamically via the `price_html` data attribute, see [SATT here](https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/display/class-wcs-att-display-product.php#L224) and [NYP here](https://github.com/woocommerce/woocommerce-name-your-price/blob/master/includes/class-wc-name-your-price-display.php#L394)

**Comment by NickGreen** [comment] 2018-06-15 15:52
@helgatheviking Thanks for filing this! I'm dealing with the same customer.

Prospress ticket for internal reference: https://secure.helpscout.net/conversation/595372275/10227/?folderId=1524435

**Comment by franticpsyx** [comment] 2018-06-16 13:52
@helgatheviking NYP isn't currently tested or supported by SATT. Happy to keep monitoring the situation with you and maybe add this to our to-do list here later on? Closing for now.

**Closed by franticpsyx** 2018-06-16 13:52 UTC

**Comment by helgatheviking** [comment] 2018-06-16 23:09
@franticpsyx could you leave this open? I'll certainly help out with it, but not until I'm back in the USA, so a week from now at the earliest.

**Comment by franticpsyx** [comment] 2018-06-19 03:10
@helgatheviking if you want to declare support for SATT on the NYP side, then I'll be happy to help you and/or review/merge a PR, if needed. However, at this moment I'm a bit reluctant to make NYP officially supported on the SATT side. We can keep the discussion going here -- I'm only closing because technically speaking, this isn't SATT responsibility.

**Comment by danielbair** [comment] 2018-06-19 06:16
FYI, I have SATT and NYP working on my donation site, nothing special. I think the issue is NYP Variations specifically.

**Comment by helgatheviking** [comment] 2018-06-19 07:08
Yes, the problem is specifically with NYP variations.

**Comment by max-quirk** [comment] 2018-06-20 00:50
Hi there, 
We are pressed for time on this issue and were wondering who we should contact on the NYP side of things to get this resolved as quickly as possible. @franticpsyx @NickGreen @franticpsyx 

Cheers, 
Max

**Comment by helgatheviking** [comment] 2018-06-20 10:39
@max-quirk I'm the developer of NYP, so I'm already aware of the non-compatibility. SATT isn't willing to declare explicit support in their plugin and I can't promise yet that I will be adding explicit support in NYP either, which leaves us in custom coded "bridge plugin" territory. Eventually I will take a look at see just how involved compatibility is, but I am currently on vacation so not going to be working on this right away. If you need it immediately you will have to develop it yourself or hire someone to do so.
