### ISSUE TITLE
Shop disappeared

### ISSUE THREAD

**Issue by sghiyam** [Prospress/woocommerce-subscribe-all-the-things#272] opened 2018-02-09 23:19 UTC
Hi all - I am so new to all this. I bow down to all of you doing this for a living... wow

WC suggested this mini add in. I uploaded it and used the Subscribe feature. About 2 minutes later my shop stopped loading, any ideas?

**Comment by willgorham** [comment] 2018-02-09 23:30
This is a good place to start: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Comment by franticpsyx** [comment] 2018-02-12 14:35
Hey @sghiyam

This is a very general issue that could be caused by a number of things. I'd start by ensuring that you are running the latest versions of 

* WooCommerce, 
* Subscriptions and 
* Subscribe All The Things

With this out of the way:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce, WCS and SATT. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

To avoid causing any problems to your live site, the best way to do this would be to try setting up a staging site, for example using a plugin such as <a href="https://wordpress.org/plugins/wp-staging/">WP Staging</a> or <a href="https://wordpress.org/plugins/duplicator/">Duplicator</a> -- and then troubleshoot the issue on the staging site.

Note that some hosts provide a Control Panel option for creating development/staging sites easily -- if you are not sure about this, it might be worth asking your host as this is definitely the easiest and fastest way to do it.

If you have access to your server's logs, it might help to look there and see what's logged when you try to load a page.

Closing for now as this issue tracker is meant to be used for reporting issues that developers can replicate.

**Closed by franticpsyx** 2018-02-12 14:35 UTC
