### ISSUE TITLE
Interval output issue

### ISSUE THREAD

**Issue by Geert46** [Prospress/woocommerce-subscribe-all-the-things#110] opened 2017-04-07 08:45 UTC
When selecting multiple outputs (month + days + weeks + years), it only shows the first interval, multiple times. For example:

Subscription options:
1) Interval: every month
2) Interval: every week
3) Interval: every 2 days
4) etc

Returns:

Choose a subscription plan:

    None – € 5,00 – subscription plans available	
    Every month
    Every month 
    Every month 
    Etc 

I believe it is an incorrect call of $option in satt-product-options.php
foreach ( $options as $option_id => $option ) {
Maybe $option is not variable anymore?

It must be due to the update of Woocommerce and Woocommerce Subscriptions since last update of SATT.

Any idea how to fix this?

**Comment by franticpsyx** [comment] 2017-04-07 08:53
@Geert46 -- Are you experiencing this issue with v1.1.2? 

SATT v1 is not tested with and does not support WC 3.0 or WCS 2.2. See #96 . 

If you depend on SATT, it is recommended to stick with WC 2.6 / WCS 2.1 until a final SATT 2.0 release is available. Feel free to take the `2.0` branch for a spin -- that one should be compatible with WC 3.0 / WCS 2.2. But note that it's still in alpha state.

**Comment by Geert46** [comment] 2017-04-07 09:02
@franticpsyx Thanks for the respons mate! It's an issue with the combination of SATT 1.1.2 and WC 3.0.0 and WCS 2.2.2

The issue shows after updating, therefore this thread. I tested it with 2.0 branch and that works! My fault for not testing this branch first.

**Comment by franticpsyx** [comment] 2017-04-07 09:13
Thanks @Geert46 -- note that 2.0 is in active development. If you notice anything strange, you are more than welcome to report it. Just make sure you the issue is still there when using the latest version of the `2.0` branch.

**Comment by franticpsyx** [comment] 2017-04-11 07:41
Closing as v1 has known issues with WC 3.0 / WCS 2.2.

**Closed by franticpsyx** 2017-04-11 07:41 UTC
