### ISSUE TITLE
turn off "Mixed Checkout" does not work properly

### ISSUE THREAD

**Issue by ash-f** [Prospress/woocommerce-subscribe-all-the-things#76] opened 2016-11-11 06:48 UTC
notice show up that subscription has been removed from cart when try to add mixed item but actually not removed.

**Comment by franticpsyx** [comment] 2016-11-26 06:04
@ash-f Could please you provide more details?

**Comment by ash-f** [comment] 2016-11-26 06:16
1. Uncheck  Woocommerce -> Subscriptions -> Mixed Checkout
2. Add regular product/Subscription to cart.
3. Add another product that is different type to cart.
4. I see "A subscription has been removed from your cart" message
5. Go to cart, I see both items are there.

**Comment by franticpsyx** [comment] 2016-11-30 15:49
Thanks @ash-f -- we have tracked down the cause and will be adding a patch for this in WooCommerce Subscriptions. 

Note that some additional work might be needed to prevent multiple SATT products from being added to the cart and converted to subscriptions there.

Closing here since this needs to be patched in WC Subscriptions.

**Closed by franticpsyx** 2016-11-30 15:49 UTC

**Comment by scottmazza** [comment] 2018-06-06 19:10
Hi. Just purchased and installed the extension and I'm still seeing this issue.
