### ISSUE TITLE
Showing subscription options twice on product page

### ISSUE THREAD

**Issue by kanermichael** [Prospress/woocommerce-subscribe-all-the-things#391] opened 2018-11-26 11:30 UTC
We have an online store, where we have been using subscribe all things for all of our products. It works great when it's a simple product. We are now trying to implement subscriptions onto variable products and when activating that, we get the options showing twice on out product page. Any Ideas to how to solve this issue would be greatly appreciated. 
![screen shot 2018-11-26 at 12 30 14](https://user-images.githubusercontent.com/8055113/49011557-1295a780-f177-11e8-9f37-cdeb82a62b80.png)

**Comment by franticpsyx** [comment] 2018-12-29 00:15
Hey @kanermichael -- we tried to replicate this locally without success. The code looks good to me, so my best guess is that this might be caused by a theme/plugin conflict.

Here's how to address this type of issue:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

Closing, but feel free to add further details here if needed.

**Closed by franticpsyx** 2018-12-29 00:15 UTC
