### ISSUE TITLE
Payment gateway does not recognise subscription product in order

### ISSUE THREAD

**Issue by cturnbull** [Prospress/woocommerce-subscribe-all-the-things#365] opened 2018-10-18 12:51 UTC
I have installed SATT and think it's genius. This is how subscriptions should be, in my opinion. 

I want the payment gateway I'm using to be compatible with it, but for some inane reason, it doesn't seem to recognise that the basket has subscription products in it, and creates only a regular order without a subscription. To be clear, WC shows the recurring totals on the cart page. It just doesn't make a subscription out of it.

I have delved a little into the payment gateway code and seen that it's using the static method `WC_Subscriptions_Product::is_subscription()`, of which I believe SATT hooks into `woocommerce_is_subscription` filter, so it looks like it's "doing it right" - but I don't know what to look for from here.

It could also be, on the other hand, that the payment gateway, which only just released recurring payment support, hasn't got quite everything quite right yet - but it's always difficult figuring out who to ask for help when there's two plugins that don't work well with each other yet.

I'd like to ask then, what is required of a payment gateway plugin to be compatible with SATT?

Thanks for your time.

**Comment by cturnbull** [comment] 2018-10-18 12:56
For what it's worth, the payment gateway in question is [Klarna Checkout for WooCommerce](https://github.com/krokedil/klarna-checkout-for-woocommerce).

**Comment by thenbrent** [comment] 2018-10-19 00:46
> I'd like to ask then, what is required of a payment gateway plugin to be compatible with SATT?

There shouldn't be anything special required from the payment gateway.

If it supports creating subscriptions with subscription products, it _should_ support creating subscriptions from product with subscription schemes via SATT.

That said, each gateway is different, so if the gateway is doing something like checking whether the cart contains a subscription before SATT has filtered that the cart contains subscriptions, additional compatibility work will be required.

> It could also be, on the other hand, that the payment gateway, which only just released recurring payment support, hasn't got quite everything quite right yet 

The easiest way to check that is to test the purchase of a standard subscription product. If a subscription is created, then its a SATT compatibility issue with the gateway. If the subscription isn't created, then it's strictly an issue with gateway extension.

Because at this stage, I'm quite confident the issue is likely either a compatibility issue or an issue an issue with that specific gateway, I'm going to close this Issue. Please feel free to loop in myself and @franticpsyx on an issue on the [Klarna repo](https://github.com/krokedil/klarna-checkout-for-woocommerce) and we can work with Niklas to get the two working well together.

**Closed by thenbrent** 2018-10-19 00:46 UTC
